apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-web-app
  name: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  strategy: {}
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
      - image: 895243719651.dkr.ecr.ap-northeast-1.amazonaws.com/node-web-app:0.0.1
        name: node-web-app
        resources: {}
